### ISSUE TITLE
구독 페이지 버튼 이벤트 생성

### ISSUE THREAD

**Issue by YongHeonJeong5842** [0417yjy/InfectionMonitoringSystem#10]
11/ 10 meeting

**Comment by 0417yjy** [comment]
* 버튼 누르면 모달 창으로 Form 나오도록 (프로토타입 참고)
* 폼 내용은 제출 버튼을 제외하고 같으므로 폼을 2개 만들지 말고, 하나만 만들어서 두 구독 버튼이 같은 것을 로딩하되, 제출 버튼만 동적으로 변경할 것
* 행정 구역은 [대한민국의 행정 구역 - 위키백과](https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD%EC%9D%98_%ED%96%89%EC%A0%95_%EA%B5%AC%EC%97%AD) 를 참고해서 나눌 것.
1. 전체/특별시/광역시/도
2. 전체/구/군/시
3. 전체/동/읍
* 가능하면 '전체' 옵션을 선택하면 하위 옵션들은 비활성화 시키기

**Comment by YongHeonJeong5842** [comment]
ㅜㅜ
